### ISSUE TITLE
Failed to activate the navigator-godef package

### ISSUE THREAD

**Issue by joefrancia** [joefitzgerald/navigator-godef#2]
[Enter steps to reproduce below:]
1. Applied Atom update from 1.6.0 to 1.6.1
2. Restarted Atom

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: [navigator-godef](https://github.com/joefitzgerald/navigator-godef) package, v1.0.2
### Stack Trace

Failed to activate the navigator-godef package

```
At _navigationStack.NavigationStack is not a function

TypeError: _navigationStack.NavigationStack is not a function
    at new Godef (/Users/joefrancia/.atom/packages/navigator-godef/lib/godef.js:15:28)
    at Object.activate (/Users/joefrancia/.atom/packages/navigator-godef/lib/main.js:20:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.5.2
atom-html-preview, v0.1.19
autocomplete-go, v1.0.5
autocomplete-php, v0.3.7
builder-go, v1.0.0
color-picker, v2.1.1
environment, v1.2.0
file-icons, v1.6.19
fountain, v0.2.0
go-config, v1.1.2
go-get, v1.0.2
go-plus, v4.1.0
go-rename, v0.3.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
highlight-line, v0.11.1
ide-haskell-cabal, v1.1.0
language-haskell, v1.7.7
language-ini, v1.15.0
language-nginx, v0.6.1
linter, v1.11.4
linter-csslint, v1.3.2
linter-pep8, v1.2.1
linter-php, v1.2.0
linter-tidy, v2.1.0
local-history, v3.2.3
minimap, v4.21.0
minimap-git-diff, v4.2.0
minimap-pigments, v0.2.0
navigator-godef, v1.0.2
pigments, v0.26.0
project-manager, v2.8.0
remote-edit, v1.8.24
symbols-tree-view, v0.11.0
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5
tester-go, v1.0.3

# Dev
No dev packages
```

**Comment by thrasher-** [comment]
I had this same issue, I simply trashed the packages in .atom, reinstalled and now it's working fine.

**Comment by joefitzgerald** [comment]
This package is deprecated. Please ensure you are running the latest version of Atom, and go-plus, and uninstall this package.
