### ISSUE TITLE
Uncaught TypeError: this.goget.register is not a function

### ISSUE THREAD

**Issue by ramigg** [joefitzgerald/navigator-godef#23]
[Enter steps to reproduce below:]
1. I updated go-plus from 4.2.0 to 4.3.2

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: "openSUSE Tumbleweed
**Thrown From**: [navigator-go](https://github.com/joefitzgerald/navigator-go) package, v1.1.3
### Stack Trace

Uncaught TypeError: this.goget.register is not a function

```
At /home/ramigg/.atom/packages/navigator-go/lib/main.js:68

TypeError: this.goget.register is not a function
    at Object.registerTool (/home/ramigg/.atom/packages/navigator-go/lib/main.js:68:39)
    at Object.consumeGoget (/home/ramigg/.atom/packages/navigator-go/lib/main.js:61:10)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Commands

```
     -6:11 go-debug:toggle-panel (atom-text-editor.editor.is-focused.vim-mode-plus.insert-mode)
     -6:01.4.0 core:save (atom-text-editor.editor.is-focused.vim-mode-plus.insert-mode)
     -5:57 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.5 (active)
apathy-theme, v1.10.6 (inactive)
atom-beautify, v0.29.13 (active)
autocomplete-ctags, v0.4.1 (active)
autocomplete-go, v1.2.0 (active)
builder-go, v1.0.1 (active)
cursor-history, v0.6.1 (active)
environment, v1.2.0 (active)
file-icons, v1.7.20 (active)
git-control, v0.8.2 (inactive)
git-plus, v5.18.0 (active)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
go-hyperclick, v1.1.0 (active)
go-imports, v0.1.1 (inactive)
go-plus, v4.3.2 (active)
godoc, v0.4.0 (active)
gofmt, v1.1.8 (active)
gometalinter-linter, v1.1.1 (active)
gorename, v1.0.3 (active)
hyperclick, v0.0.38 (active)
imdone-atom, v1.3.31 (active)
linter, v1.11.16 (active)
minimap, v4.25.0 (active)
nav-panel-plus, v0.1.3 (active)
navigator-go, v1.1.3 (inactive)
navigator-godef, v1.0.4 (inactive)
platformio-ide-terminal, v2.2.0 (active)
sync-settings, v0.7.2 (active)
tasks, v2.6.3 (active)
tester-go, v1.0.6 (active)
vim-mode-plus, v0.57.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lloiser** [comment]
Maybe `navigator-go` was updated before `go-get` has been updated.
Try reloading atom.

**Comment by ramigg** [comment]
after reloading atom it seams to be ok.

Thanks!

**Comment by joefitzgerald** [comment]
This package is deprecated. Please ensure you are running the latest version of Atom and go-plus, and uninstall this package.
