### ISSUE TITLE
Failed to activate the navigator-godef package

### ISSUE THREAD

**Issue by monstar316** [joefitzgerald/navigator-godef#31]
1. As navigator-godef wasn't available from packages (https://atom.io/packages), I manually downloaded it and exported it to the packages folder within %USERPROFILE%\.atom\packages
2. Opened up Atom and got the below error in relation to navigator-godef.

Atom: 1.19.7 ia32
Electron: 1.6.9
OS: Microsoft Windows 10 Pro
Thrown From: navigator-godef 1.0.3

Stack Trace

Failed to activate the navigator-godef package

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/Ricky/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:40:43)
    at require (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\native-compile-cache.js:66:33)
    at Object.activate (file:///C:/Users/Ricky/.atom/packages/navigator-go/lib/main.js:14:5)
    at Package.module.exports.Package.activateNow (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package.js:253:25)
    at C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package.js:99:21)
    at C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package-manager.js:645:40)
    at C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\package-manager.js:603:52)
    at C:\Users\Ricky\AppData\Local\atom\app-1.19.7\resources\app\src\atom-environment.js:843:36

**Comment by lloiser** [comment]
This package is deprecated. It has been replaced by [`go-plus`](https://github.com/joefitzgerald/go-plus)
